{% set name = "pyxpcm" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/obidam/pyxpcm/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 686027610223a717a63af6b5d5fe41ea953bbc942c68050afad11a649370f75f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scipy >=1.1.0
    - xarray >=0.12.1
    - scikit-learn >=0.21
    - ipython >=5.0.0
    - numpydoc >=0.6.0
    - netcdf4 >=1.3.1
    - dask-core >=0.16.0
    - toolz >=0.8.2

test:
  imports:
    - pyxpcm
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/obidam/pyxpcm
  summary: 'pyxpcm: Ocean Profile Classification Model'
  license: GPL-3.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
